---
- hosts: all
  become: true

  tasks:
    - name: Install aptitude using apt
      apt:
        name: aptitude
        state: present
        update_cache: true
        force_apt_get: yes

    - name: Install required system packages
      apt:
        name: {{ item }}
        state: present
        update_cache: true
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Verify that we have the key with the fingerprint
      remote_user: ubuntu
      apt_key:
        id: 0EBFCD88
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      apt:
        update_cache: true
        name: docker-ce
        state: present

    - name: Add remote "ubuntu" user to "docker" group
      remote_user: ubuntu
      user:
        name: "ubuntu"
        group: "docker"
        append: yes
      tags:
        - docker
        - name: Install docker-compose
          remote_user: ubuntu
          get_url:
            url: https://github.com/docker/compose/releases/download/1.25.1-rc1/docker-compose-Linux-x86_64
            dest: /usr/local/bin/docker-compose
            mode: 'u+x,g+x'
